name: Build binaries (Windows, Linux, macOS)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install PySide6

      # ---------------- WINDOWS ----------------
      - name: Build binary (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          # Pfad zu hl7apy dynamisch bestimmen
          $hl7path = python -c "import hl7apy, os; print(os.path.dirname(hl7apy.__file__))"
          
          # PyInstaller aufrufen
            pyinstaller `
          --windowed `
          --onefile `
          --name HL7-Lookup `
          --noconsole `
          --collect-all PySide6 `
          --icon=hl7.ico `
          --add-data=stylesheet.qss:. `
          --add-data=hl7.ico:. `
          --add-data=SourceCodePro-Light.ttf:. `
          --add-data=$hl7path`:hl7apy `
          --collect-all=hl7apy `
          --clean `
          main.py
          
          mkdir -p build-artifacts/windows
          copy dist\HL7-Lookup.exe build-artifacts\windows\
      # ---------------- LINUX ----------------
      - name: Build binary (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          pyinstaller --windowed --name HL7-Lookup --noconsole --onefile --icon=hl7.ico --collect-all PySide6 --add-data "stylesheet.qss:." --add-data "hl7.ico:." --clean --collect-all hl7apy --add-data "SourceCodePro-Light.ttf:." main.py

          mkdir -p build-artifacts/linux
          cp dist/HL7-Lookup build-artifacts/linux/main
          
      # ---------------- MACOS ----------------
      - name: Build binary (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          pyinstaller --windowed --name HL7-Lookup --noconsole --onedir --icon=hl7.ico --add-data "stylesheet.qss:." --add-data "hl7.ico:." --clean --collect-all hl7apy --add-data "SourceCodePro-Light.ttf:." main.py
          
          mkdir -p build-artifacts/macos
          cp -r dist/HL7-Lookup build-artifacts/macos/
          
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-${{ matrix.os }}
          path: build-artifacts/
